### PR TITLE
Add label and dash for no data

### PR DESCRIPTION
**Pull request by xinsight**
I noticed that there was an unused UILabel, so it's being updated and I added a property to display it.

I also found it useful when there wasn't any data (or invalid data) to show just a dash [–], so that option is also included.

There's a few tweaks to the example so that thes changes can be seen: A label is enabled on one progress indicator and a slight pause at 100.

### CODE REVIEW

**Comment by tiagomnh** [comment]
First and foremost, thank you for spending the time to do this. I really appreciate it. 

Regarding the center label, yeah, I should document it someday. My bad. I want, however, to keep THCIrcularProgressView a very generic and simple progress view. If the developer wants to use the `centerLabel` to display the percentage numerically, then he should set `centerLabel.text` when he sets the view's percentage property. The view itself should not do it automatically.

Let me know what you think!

**Comment by xinsight** [comment]
Manually updating the label is a bit error prone - (e.g. if the progress is set in two places, you have to duplicate that formatting code), but it certainly is more flexible. I agree not everyone will want to show a percentage.

I'd still recommend the pulling the [isLabelVisible](https://github.com/xinsight/THCircularProgressView/commit/a6e6dcdbf761476e2a32c0fe5bf9e2c1135a43e6) commit. It hides the label by default which is a nice performance increase - particularly useful if the circular progress is being used in a table cell. Here's a couple of shots from the simulator with "Color blended images". (Red is bad.)

blend-orig
blend-patch

**Comment by xinsight** [comment]
Just noticed that the formatting line is still in that first commit. That should be removed.

`_centerLabel.text = [NSString stringWithFormat:@"%.0f", percentage*100.0f];`

**Comment by tiagomnh** [comment]
Agree. I've merged that commit in. Thanks! :+1:

**Pull request closed without merging**
